name: UHC
version: 0.3
author: Quozul
main: dev.quozul.UHC.Main
api-version: 1.19

commands:
  start:
    description: Start UHC game
    usage: /start <duration> <border radius>
    default:
  jointeam:
    description: Join UHC team
    usage: /jointeam [team name]
    default:
  selectteam:
    description: Select team
    usage: /selectteam
    default:
  regenerateworlds:
    description: Regen UHC worlds
    usage: /regenerateworlds
    default:
  spawnchest:
    description: Spawn a chest where you are
    usage: /spawnchest
    default: